In [2]:
import numpy as np 

In [3]:
array1 = np.array([1,2,3,4,5,6,7,8])

In [4]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
array_3d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

In [6]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
array1[2:5]

array([3, 4, 5])

In [9]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
array1[3:-1]

array([4, 5, 6, 7])

In [11]:
array1[-3:-1]

array([6, 7])

In [12]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
array1[-8:-1]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
array1[2:5]

array([3, 4, 5])

In [16]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
array1[3:5:]

array([4, 5])

In [20]:
array_2d = np.array([[1,2,3],[4,5,6]])

In [25]:
array_2d[1,2:]

array([6])

In [30]:
array_2d[-2:-3:-1]

array([[1, 2, 3]])