In [217]:
import numpy as np 
import pandas as pd 
from sklearn.impute import SimpleImputer

In [218]:
d1 = pd.read_csv('dataset1.csv')

In [219]:
print(d1.describe())

             Age        Salary
count  11.000000     12.000000
mean   35.363636  62166.666667
std     6.888726  14837.503670
min    27.000000  38000.000000
25%    30.500000  51000.000000
50%    35.000000  61000.000000
75%    39.000000  73750.000000
max    48.000000  85000.000000


Create dependent and independent vairable vectors

Slicing the last boolean col from the dataframe with -1 command and saving as x.
Here, x is the independent variable.

In [220]:
x = d1.iloc[:,:-1].values       

Notice that in the previous section had the : before -1 which which indicated slicing, but here only the -1 is used depicting only the last bool col is taken and saved in y.
Here, y is the dependent variable.

In [221]:
y = d1.iloc[:,-1].values       

In [222]:
print(x)

[['Mumbai' 27.0 51000.0]
 ['New York' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['New York' nan 66000.0]
 ['Tokyo' 48.0 nan]
 ['Tokyo' nan 51000.0]
 ['Singapore' 33.0 69000.0]
 ['New York' 40.0 79000.0]
 ['Mumbai' 38.0 nan]
 ['Singapore' 35.0 38000.0]
 ['Tokyo' nan 56000.0]
 ['Singapore' 35.0 72000.0]
 ['New York' 45.0 79000.0]
 ['Mumbai' 31.0 85000.0]]


In [223]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes'
 'Yes']


In [224]:
print(d1.isnull().sum())

City                     0
Age                      3
Salary                   2
Eligibility for bonus    0
dtype: int64


Practice of using dropna.
It's not gonna be used in the main process.

Notice that we're dropping only the rows that are on main dataframe rather than the splitted dataframe which are x and y

In [225]:
d1.dropna(inplace=True)   

In [226]:
print(d1)

         City   Age   Salary Eligibility for bonus
0      Mumbai  27.0  51000.0                   Yes
1    New York  27.0  48000.0                   Yes
2      Mumbai  30.0  52000.0                    No
6   Singapore  33.0  69000.0                    No
7    New York  40.0  79000.0                   Yes
9   Singapore  35.0  38000.0                    No
11  Singapore  35.0  72000.0                    No
12   New York  45.0  79000.0                   Yes
13     Mumbai  31.0  85000.0                   Yes


Handling missing values

The function is used for handling missing values, we will use it in splitted dataframes (x,y).
Here, the strategy value is usually used 'mean', but we can also use std, min, max etc

In [227]:
imputer = SimpleImputer(missing_values=np.NaN, strategy='mean')

In [228]:
print(x)

[['Mumbai' 27.0 51000.0]
 ['New York' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['New York' nan 66000.0]
 ['Tokyo' 48.0 nan]
 ['Tokyo' nan 51000.0]
 ['Singapore' 33.0 69000.0]
 ['New York' 40.0 79000.0]
 ['Mumbai' 38.0 nan]
 ['Singapore' 35.0 38000.0]
 ['Tokyo' nan 56000.0]
 ['Singapore' 35.0 72000.0]
 ['New York' 45.0 79000.0]
 ['Mumbai' 31.0 85000.0]]


In the imputer function, we are insertig the cols starting after 1st column(0, 1, 2, 3) till the 3rd col. In the 0th index, the index number of the data is stored.
After fitting the values in the impter function, we replace the new value from imputer function 
with the old value in x using transform function.

In [229]:
imputer.fit(x[:, 1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [230]:
print(x)

[['Mumbai' 27.0 51000.0]
 ['New York' 27.0 48000.0]
 ['Mumbai' 30.0 52000.0]
 ['New York' 35.36363636363637 66000.0]
 ['Tokyo' 48.0 62166.666666666664]
 ['Tokyo' 35.36363636363637 51000.0]
 ['Singapore' 33.0 69000.0]
 ['New York' 40.0 79000.0]
 ['Mumbai' 38.0 62166.666666666664]
 ['Singapore' 35.0 38000.0]
 ['Tokyo' 35.36363636363637 56000.0]
 ['Singapore' 35.0 72000.0]
 ['New York' 45.0 79000.0]
 ['Mumbai' 31.0 85000.0]]


Importing OneHotEncoder to use binary values instead of the string values from col 1 which is the name of the cities

In [231]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

Using ColumnTransformer function we can transform the string data into binary data.
In this method the must use 2 attributes are transformers and remainders.
In the transformers attribute, we have to define it is a encoder which with the value of OneHotEncoder, and then the index of the desired col in the dataframe x.
Later, the remainder attribute is defined. The default value of the remainder attribute is 'drop' which means if we use drop, the desired column will be transformed into binary data and the remaining columns will be dropped from the dataframe x which we certainly do not want. 
So, we'll use the value 'passthrough' which means that the remaining columns in the dataframe 
x will be left as they were.
Finnaly, we'll use np.array to fit the data and replace with the old data in x.
'n' number of new columns will be created in dataframe x, 'n' is the number of unique values 
from the desired index that we passed in the transformers attribute.
In the final form, each row will depict a value of '1' which means 'True' in the respected row that is indicating the column associated with the unique value from the original index of name of the cities.

In [232]:
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [233]:
print(x)

[[1.0 0.0 0.0 0.0 27.0 51000.0]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 0.0 30.0 52000.0]
 [0.0 1.0 0.0 0.0 35.36363636363637 66000.0]
 [0.0 0.0 0.0 1.0 48.0 62166.666666666664]
 [0.0 0.0 0.0 1.0 35.36363636363637 51000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]
 [0.0 1.0 0.0 0.0 40.0 79000.0]
 [1.0 0.0 0.0 0.0 38.0 62166.666666666664]
 [0.0 0.0 1.0 0.0 35.0 38000.0]
 [0.0 0.0 0.0 1.0 35.36363636363637 56000.0]
 [0.0 0.0 1.0 0.0 35.0 72000.0]
 [0.0 1.0 0.0 0.0 45.0 79000.0]
 [1.0 0.0 0.0 0.0 31.0 85000.0]]


Importing LabelEncoder to transform the 2 possible values in the bool col in the dependent variable that we seperated and saved as y.
In this case, there could be 2 possible values which are 'True' and 'False'. So, we'll replace these 2 values with the labels 0,1.

In [234]:
from sklearn.preprocessing import LabelEncoder

In [235]:
print(y)

['Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'Yes'
 'Yes']


The variable le is used to instantiate the constructor LabelEncoder(). 
We then used the fit_transform function to fit the data in the LabelEncoder and replaced the new data with the old data in y.

In [236]:
le = LabelEncoder()
y = le.fit_transform(y)


In [237]:
print(y)

[1 1 0 0 1 0 0 1 1 0 0 0 1 1]


Splitting dataset into train and test set

In [238]:
from sklearn.model_selection import train_test_split

In [239]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [240]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 0.0 30.0 52000.0]
 [0.0 0.0 0.0 1.0 35.36363636363637 56000.0]
 [0.0 0.0 0.0 1.0 48.0 62166.666666666664]
 [0.0 1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 45.0 79000.0]
 [1.0 0.0 0.0 0.0 27.0 51000.0]
 [1.0 0.0 0.0 0.0 31.0 85000.0]
 [0.0 0.0 1.0 0.0 35.0 38000.0]
 [1.0 0.0 0.0 0.0 38.0 62166.666666666664]
 [0.0 0.0 1.0 0.0 35.0 72000.0]
 [0.0 0.0 0.0 1.0 35.36363636363637 51000.0]]
[[0.0 1.0 0.0 0.0 35.36363636363637 66000.0]
 [0.0 1.0 0.0 0.0 40.0 79000.0]
 [0.0 0.0 1.0 0.0 33.0 69000.0]]
[0 0 1 1 1 1 1 0 1 0 0]
[0 1 0]


Feature Scaling

If we look at the data we've got, we can see that the scale the values are in, they're not same or close to be fair enough. So, to get the best results we need to put all the data we have into the same scale and that is what feature scaling is.

There're 2 forms of feature scaling, which are standardization and normalization.
But when do we use which one? Standardization works on any kind of data where we can use the normalization method only when the data is normally distributed.

Here, in this case, we are going to use standardization.
Usually, the scale of standardization is between -3 and +3.

In [241]:
from sklearn.preprocessing import StandardScaler

In [242]:
scaler = StandardScaler()
x_train[:,4:] = scaler.fit_transform(x_train[:,4:])
x_test[:,4:] = scaler.fit_transform(x_test[:,4:])
print(x_train)
print(x_test)

[[1.0 0.0 0.0 0.0 -0.808993598746295 -0.5674179192969602]
 [0.0 0.0 0.0 1.0 0.032411602513874406 -0.27137378748985014]
 [0.0 0.0 0.0 1.0 2.0147052122624074 0.1850275823794443]
 [0.0 1.0 0.0 0.0 -1.2796100672477455 -0.8634620511040701]
 [0.0 1.0 0.0 0.0 1.544088743760957 1.4308799704010324]
 [1.0 0.0 0.0 0.0 -1.2796100672477455 -0.6414289522487376]
 [1.0 0.0 0.0 0.0 -0.6521214425791448 1.8749461681116975]
 [0.0 0.0 1.0 0.0 -0.02463281791054433 -1.6035723806218452]
 [1.0 0.0 0.0 0.0 0.44598365059090606 0.1850275823794443]
 [0.0 0.0 1.0 0.0 -0.02463281791054433 0.9128027397385899]
 [0.0 0.0 0.0 1.0 0.032411602513874406 -0.6414289522487376]]
[[0.0 1.0 0.0 0.0 -0.26055806683273924 -0.9596162302465067]
 [0.0 1.0 0.0 0.0 1.3340573021836235 1.3794483309793555]
 [0.0 0.0 1.0 0.0 -1.0734992353508865 -0.4198321007328462]]
